version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - echo No prebuild
  build:
    commands:
      - echo Build started on `date`
      - pip install requests -t ./
      - ls

artifacts:
  files:
    - appspec.yaml
  discard-paths: yes
