version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - echo No prebuild
  build:
    commands:
      - echo Build started on `date`
      - pip install requests -t ./
      - ls
      - export BUCKET=codepipeline-us-east-1-510222075463
      - aws cloudformation package --template-file template.yml --s3-bucket $BUCKET --output-template-file outputtemplate.yml
artifacts:
  type: zip
  files:
    - template.yml
    - outputtemplate.yml
